### ISSUE TITLE
icons_two branch

### ISSUE THREAD

**Issue by zeffii** [zeffii/mesh_tinyCAD#43]
here.. i've made a new version of the icons branch, called icons_two and it seems stable so far but I have not tested it yet. 

warning EXM / PERP are no longer included.

**Comment by Spirou4D** [comment]
Ok !

**Comment by zeffii** [comment]
![image](https://cloud.githubusercontent.com/assets/619340/15738758/0e812f7e-28ad-11e6-9946-741db3fcfa2a.png)

**Comment by zeffii** [comment]
I might make this master.. the code is a bit cleaner this time :)

**Comment by Spirou4D** [comment]
I had make a fork on my account but i wait then....Thanks Zeffii

**Comment by zeffii** [comment]
you're welcome @Spirou4D my pleasure.

**Comment by Spirou4D** [comment]
Hi Zeffii,
How to add a folder, please, I can't! ;-))

**Comment by zeffii** [comment]
If you used `git` correctly you could run a command line ` git checkout icons_two` and git would then change the files in that directory to reflect the state of the `icons_two` branch. If you aren't using `git` it's more effort for me to explain how to use it, I do not have time for that. (But worth your time to learn about git..so do.)

So the simplest approach is to download the icons_two branch, [directly from this link](https://github.com/zeffii/mesh_tinyCAD/archive/icons_two.zip) and before installing it , rename the zip from `mesh_tinyCAD-icons_two` to simply `mesh_tinyCAD`  , then install.

**Comment by Spirou4D** [comment]
no no Zeffii, you don't understand. I asck you how to add a empty folder in
the github , there are a create new file, then a button: Upload files and
Find File but not button to create a empty folder. I have uploaded the new
icons but it must go in a icons named folder.

I know to use Git but here i work online only.

---

Patrick DepoixArchitecte D.P.L.G.Historien-chercheur en histoire de
l'ArchitectureEx-Maître de conférence de l'Ecole d'Architecture de
Lille-Région NordSitArchi-ReaderNewS
<http://www.google.com/reader/shared/user%2F04161245489718164963%2Fstate%2Fcom.google%2Fstarred>

http://www.linkedin.com/pub/patrick-depoix/40/b3b/542136, rue d'Esquermes59000
LilleFranceTel   (+33/0) 952 51 33 25Port  (+33/0) 06 23 13 73 71
Skype:oikakeruPour répondre --> Mailto:patrick.depoix@gmail.com
<http://---%20http://www.linkedin.com/pub/patrick-depoix/40/b3b/542%20Patrick%20Depoix%20Architecte%20D.P.L.G.%20Historien-chercheur%20en%20histoire%20de%20l%27Architecture%20Ex-Ma%C3%AEtre%20de%20conf%C3%A9rence%20de%20l%27Ecole%20d%27Architecture%20de%20Lille-R%C3%A9gion%20Nord136,%20rue%20d%27Esquermes%2059000%20Lille%20France%20Tel%20%20%20%28+33/0%29%20952%2051%2033%2025%20Port%20%20%28+33/0%29%2006%2023%2013%2073%2071%20Fax%20%20%28+33/0%29%20826%2070%2004%2040%20Skype:oikakeru%20%20Pour%20r%C3%A9pondre%20--%3E%20Mailto:patrick.depoix@free.fr>

2016-06-06 8:37 GMT+02:00 Dealga McArdle <notifications@github.com>:

**Comment by zeffii** [comment]
oh, in your own repo you simply do create a new file, some dummy file, inside a new folder
`existing_folder/new_folder/dummy_name.txt`

**Comment by zeffii** [comment]
![gif](https://cloud.githubusercontent.com/assets/619340/15815393/0d8754d6-2bcd-11e6-95bb-c33408da169a.gif)
then commit.

**Comment by Spirou4D** [comment]
Ha YES very good, I havn't saw this feature! Great Thanks dera Zeffii!
Have a nice day.
I have made the change but remove the CFG file not really usable, only an
__init__ file is enough.
I have made a special new icon to E2F.py only.
Bye bye
Patrick

---

Patrick DepoixArchitecte D.P.L.G.Historien-chercheur en histoire de
l'ArchitectureEx-Maître de conférence de l'Ecole d'Architecture de
Lille-Région NordSitArchi-ReaderNewS
<http://www.google.com/reader/shared/user%2F04161245489718164963%2Fstate%2Fcom.google%2Fstarred>

http://www.linkedin.com/pub/patrick-depoix/40/b3b/542136, rue d'Esquermes59000
LilleFranceTel   (+33/0) 952 51 33 25Port  (+33/0) 06 23 13 73 71
Skype:oikakeruPour répondre --> Mailto:patrick.depoix@gmail.com
<http://---%20http://www.linkedin.com/pub/patrick-depoix/40/b3b/542%20Patrick%20Depoix%20Architecte%20D.P.L.G.%20Historien-chercheur%20en%20histoire%20de%20l%27Architecture%20Ex-Ma%C3%AEtre%20de%20conf%C3%A9rence%20de%20l%27Ecole%20d%27Architecture%20de%20Lille-R%C3%A9gion%20Nord136,%20rue%20d%27Esquermes%2059000%20Lille%20France%20Tel%20%20%20%28+33/0%29%20952%2051%2033%2025%20Port%20%20%28+33/0%29%2006%2023%2013%2073%2071%20Fax%20%20%28+33/0%29%20826%2070%2004%2040%20Skype:oikakeru%20%20Pour%20r%C3%A9pondre%20--%3E%20Mailto:patrick.depoix@free.fr>

2016-06-06 9:57 GMT+02:00 Dealga McArdle <notifications@github.com>:

**Comment by zeffii** [comment]
btw, I made a few changes to `cad_module.py` , and VTX, BIX.

If you really want to use icons, I suggest forking from `icons_two` instead, and pulling down the changes I made, I've added (in the next 10 minutes) the E2F icon.

**Comment by zeffii** [comment]
unfortunately I can't find the .blend I made to create the original icons : /

**Comment by Spirou4D** [comment]
All is ok now:
https://github.com/Spirou4D/mesh_tinyCAD

Main release with icons.
Byebye
Patrick

---

Patrick DepoixArchitecte D.P.L.G.Historien-chercheur en histoire de
l'ArchitectureEx-Maître de conférence de l'Ecole d'Architecture de
Lille-Région NordSitArchi-ReaderNewS
<http://www.google.com/reader/shared/user%2F04161245489718164963%2Fstate%2Fcom.google%2Fstarred>

http://www.linkedin.com/pub/patrick-depoix/40/b3b/542136, rue d'Esquermes59000
LilleFranceTel   (+33/0) 952 51 33 25Port  (+33/0) 06 23 13 73 71
Skype:oikakeruPour répondre --> Mailto:patrick.depoix@gmail.com
<http://---%20http://www.linkedin.com/pub/patrick-depoix/40/b3b/542%20Patrick%20Depoix%20Architecte%20D.P.L.G.%20Historien-chercheur%20en%20histoire%20de%20l%27Architecture%20Ex-Ma%C3%AEtre%20de%20conf%C3%A9rence%20de%20l%27Ecole%20d%27Architecture%20de%20Lille-R%C3%A9gion%20Nord136,%20rue%20d%27Esquermes%2059000%20Lille%20France%20Tel%20%20%20%28+33/0%29%20952%2051%2033%2025%20Port%20%20%28+33/0%29%2006%2023%2013%2073%2071%20Fax%20%20%28+33/0%29%20826%2070%2004%2040%20Skype:oikakeru%20%20Pour%20r%C3%A9pondre%20--%3E%20Mailto:patrick.depoix@free.fr>

2016-06-06 9:57 GMT+02:00 Dealga McArdle <notifications@github.com>:

**Comment by zeffii** [comment]
Ok. have fun!

**Comment by zeffii** [comment]
cool. I found the original .blend !  http://blender.stackexchange.com/questions/31180/material-shading-options-in-3d-viewport-limited-for-curve-objects

**Comment by Spirou4D** [comment]
Ha OK Zeffii,
I downloaded now...
Byebye
Patrick

---

Patrick DepoixArchitecte D.P.L.G.Historien-chercheur en histoire de
l'ArchitectureEx-Maître de conférence de l'Ecole d'Architecture de
Lille-Région NordSitArchi-ReaderNewS
<http://www.google.com/reader/shared/user%2F04161245489718164963%2Fstate%2Fcom.google%2Fstarred>

http://www.linkedin.com/pub/patrick-depoix/40/b3b/542136, rue d'Esquermes59000
LilleFranceTel   (+33/0) 952 51 33 25Port  (+33/0) 06 23 13 73 71
Skype:oikakeruPour répondre --> Mailto:patrick.depoix@gmail.com
<http://---%20http://www.linkedin.com/pub/patrick-depoix/40/b3b/542%20Patrick%20Depoix%20Architecte%20D.P.L.G.%20Historien-chercheur%20en%20histoire%20de%20l%27Architecture%20Ex-Ma%C3%AEtre%20de%20conf%C3%A9rence%20de%20l%27Ecole%20d%27Architecture%20de%20Lille-R%C3%A9gion%20Nord136,%20rue%20d%27Esquermes%2059000%20Lille%20France%20Tel%20%20%20%28+33/0%29%20952%2051%2033%2025%20Port%20%20%28+33/0%29%2006%2023%2013%2073%2071%20Fax%20%20%28+33/0%29%20826%2070%2004%2040%20Skype:oikakeru%20%20Pour%20r%C3%A9pondre%20--%3E%20Mailto:patrick.depoix@free.fr>

2016-06-06 10:31 GMT+02:00 Dealga McArdle <notifications@github.com>:

**Comment by zeffii** [comment]
![e2f](https://cloud.githubusercontent.com/assets/619340/15818031/56254582-2bdb-11e6-8ab5-024579846c0d.png)

**Comment by zeffii** [comment]
script used
```python
import os
import subprocess


def generate(from_file, x, y, filenames, kind='.png'):
    filenames = filenames.split()

    yield "C:\\Program Files\\ImageMagick-7.0.1-Q16\\convert.exe {0} local01.miff".format(from_file)
    for i, filename in enumerate(filenames):
        l = "C:\\Program Files\\ImageMagick-7.0.1-Q16\\convert.exe local01.miff -crop {0}x{1}+{2}+0 {3}{4}"
        yield l.format(x, y, i * x, filename, kind)
    

def main():
    with open('local01.tff', 'w') as m:
        print('generated local file')

    rendered_name = 'RENDERED_ARRAY.PNG'
    icons = "VTX V2X XALL BIX E2F CCEN EXM"
    file_strings = generate(rendered_name, 32, 32, icons)
    for line in file_strings:
        try:
            subprocess.Popen(line.split())
        except:
            print('failed:', line.split())

    # os.remove("local01.miff")
    # os.remove("local01.tff")


main()
```

**Comment by zeffii** [comment]
because the script spawns subprocesses, the final removal of the temoirary files (local01.miff .tff) could sometimes happen before the icon subprocesses start. So commented it out and ignore those.

**Comment by Spirou4D** [comment]
Ok I have take note.
bye.

---

Patrick DepoixArchitecte D.P.L.G.Historien-chercheur en histoire de
l'ArchitectureEx-Maître de conférence de l'Ecole d'Architecture de
Lille-Région NordSitArchi-ReaderNewS
<http://www.google.com/reader/shared/user%2F04161245489718164963%2Fstate%2Fcom.google%2Fstarred>

http://www.linkedin.com/pub/patrick-depoix/40/b3b/542136, rue d'Esquermes59000
LilleFranceTel   (+33/0) 952 51 33 25Port  (+33/0) 06 23 13 73 71
Skype:oikakeruPour répondre --> Mailto:patrick.depoix@gmail.com
<http://---%20http://www.linkedin.com/pub/patrick-depoix/40/b3b/542%20Patrick%20Depoix%20Architecte%20D.P.L.G.%20Historien-chercheur%20en%20histoire%20de%20l%27Architecture%20Ex-Ma%C3%AEtre%20de%20conf%C3%A9rence%20de%20l%27Ecole%20d%27Architecture%20de%20Lille-R%C3%A9gion%20Nord136,%20rue%20d%27Esquermes%2059000%20Lille%20France%20Tel%20%20%20%28+33/0%29%20952%2051%2033%2025%20Port%20%20%28+33/0%29%2006%2023%2013%2073%2071%20Fax%20%20%28+33/0%29%20826%2070%2004%2040%20Skype:oikakeru%20%20Pour%20r%C3%A9pondre%20--%3E%20Mailto:patrick.depoix@free.fr>

2016-06-06 12:03 GMT+02:00 Dealga McArdle <notifications@github.com>:

**Comment by Spirou4D** [comment]
Bonjour zeffii/mesh_tinyCAD,
Patrick Depoix vous a laissé un message sur IQ Elite 
Cliquez ici a.iqelite.com/j/KguAQP/xav/?hg=PfYywTq6KO pour lire votre message 


L'équipe d'IQ Elite



---------------------------------------------------------------------------
Ce message est destiné à reply@reply.github.com. Si vous ne souhaitez pas recevoir d'autres messages de la part de IQ Elite, veuillez cliquer sur ce lien : a.iqelite.com/common/unsubscribe/?code=fd62cbb6&email=reply@reply.github.com.&hg=PfYywTq6KO
IQ Elite est un service de IQ Elite S.L., dont le siège se trouve à : C/ Gran De Gràcia 15, 1a 1a, 08012 Barcelone, Espagne. 
---------------------------------------------------------------------------

**Comment by zeffii** [comment]
@Spirou4D I think some app has your github password / rights to paste in your name. scary!

**Comment by Spirou4D** [comment]
You are right Zeffi, I go to remove this scary IQ Elite forum now...
I apologize for the inconvenience.
At soon.
Patrick

---

Patrick DepoixArchitecte D.P.L.G.Historien-chercheur en histoire de
l'ArchitectureEx-Maître de conférence de l'Ecole d'Architecture de
Lille-Région NordSitArchi-ReaderNewS
<http://www.google.com/reader/shared/user%2F04161245489718164963%2Fstate%2Fcom.google%2Fstarred>

http://www.linkedin.com/pub/patrick-depoix/40/b3b/542136, rue d'Esquermes59000
LilleFranceTel   (+33/0) 952 51 33 25Port  (+33/0) 06 23 13 73 71
Skype:oikakeruPour répondre --> Mailto:patrick.depoix@gmail.com
<http://---%20http://www.linkedin.com/pub/patrick-depoix/40/b3b/542%20Patrick%20Depoix%20Architecte%20D.P.L.G.%20Historien-chercheur%20en%20histoire%20de%20l%27Architecture%20Ex-Ma%C3%AEtre%20de%20conf%C3%A9rence%20de%20l%27Ecole%20d%27Architecture%20de%20Lille-R%C3%A9gion%20Nord136,%20rue%20d%27Esquermes%2059000%20Lille%20France%20Tel%20%20%20%28+33/0%29%20952%2051%2033%2025%20Port%20%20%28+33/0%29%2006%2023%2013%2073%2071%20Fax%20%20%28+33/0%29%20826%2070%2004%2040%20Skype:oikakeru%20%20Pour%20r%C3%A9pondre%20--%3E%20Mailto:patrick.depoix@free.fr>

2016-08-07 10:15 GMT+02:00 Dealga McArdle <notifications@github.com>:

**Comment by zeffii** [comment]
@Spirou4D ps, tinyCAD will be included in the next release version of blender in scripts/addons/mesh_tiny_cad (it includes icons!)

**Comment by Spirou4D** [comment]
Really, I am happy for you, Zeffi! Congratulations.
At soon.
Spirou4D

PS: IQ ELITE Forum removed!

---

Patrick DepoixArchitecte D.P.L.G.Historien-chercheur en histoire de
l'ArchitectureEx-Maître de conférence de l'Ecole d'Architecture de
Lille-Région NordSitArchi-ReaderNewS
<http://www.google.com/reader/shared/user%2F04161245489718164963%2Fstate%2Fcom.google%2Fstarred>

http://www.linkedin.com/pub/patrick-depoix/40/b3b/542136, rue d'Esquermes59000
LilleFranceTel   (+33/0) 952 51 33 25Port  (+33/0) 06 23 13 73 71
Skype:oikakeruPour répondre --> Mailto:patrick.depoix@gmail.com
<http://---%20http://www.linkedin.com/pub/patrick-depoix/40/b3b/542%20Patrick%20Depoix%20Architecte%20D.P.L.G.%20Historien-chercheur%20en%20histoire%20de%20l%27Architecture%20Ex-Ma%C3%AEtre%20de%20conf%C3%A9rence%20de%20l%27Ecole%20d%27Architecture%20de%20Lille-R%C3%A9gion%20Nord136,%20rue%20d%27Esquermes%2059000%20Lille%20France%20Tel%20%20%20%28+33/0%29%20952%2051%2033%2025%20Port%20%20%28+33/0%29%2006%2023%2013%2073%2071%20Fax%20%20%28+33/0%29%20826%2070%2004%2040%20Skype:oikakeru%20%20Pour%20r%C3%A9pondre%20--%3E%20Mailto:patrick.depoix@free.fr>

2016-08-07 12:58 GMT+02:00 Dealga McArdle <notifications@github.com>:

**Comment by Spirou4D** [comment]
Bonjour zeffii/mesh_tinyCAD,


Patrick Depoix vous a laissé un message sur IQ Elite 


Cliquez ici a.iqelite.com/j/KguAQP/xav/?hg=tEYQWfz9MF pour lire votre message 


L'équipe d'IQ Elite



---------------------------------------------------------------------------
Ce message est destiné à reply@reply.github.com. Si vous ne souhaitez pas recevoir d'autres messages de la part de IQ Elite, veuillez cliquer sur ce lien : a.iqelite.com/common/unsubscribe/?code=fd62cbb6&email=reply@reply.github.com.&hg=tEYQWfz9MF
IQ Elite est un service de IQ Elite S.L., dont le siège se trouve à : C/ Gran De Gràcia 15, 1a 1a, 08012 Barcelone, Espagne. 
---------------------------------------------------------------------------

**Comment by zeffii** [comment]
@Spirou4D  again? :)

**Comment by Spirou4D** [comment]
But my IQ Elite account is erased???? It's a publicity message yet! Don't read it, please!
I go to see the google+ account to see the autorisation....

**Comment by zeffii** [comment]
I would never visit that link :)

**Comment by Spirou4D** [comment]
could you clic this link, please:
http://a.iqelite.com/common/unsubscribe/?code=fd62cbb6&email=reply@reply.github.com.&hg=tEYQWfz9MF

**Comment by Spirou4D** [comment]
Zeffi, I am very sorry : look here please:
https://productforums.google.com/forum/#!topic/websearch-fr/TV-dWaHdmNE

OK I removed the IQ ELITE authorisation here: https://security.google.com/settings/security/permissions?hl=fr&pli=1

Now it's ok I mean!

**Comment by zeffii** [comment]
i'm not going to click anywhere @Spirou4D  :)

**Comment by zeffii** [comment]
hopefully it is resolved :)

**Comment by Spirou4D** [comment]
No ok, now it's ended because I have removed of Google+.
I didn't know that! It's just a form that a friend sent me and this site plundered my mails!!!!

**Comment by zeffii** [comment]
very scary stuff. take care @Spirou4D

**Comment by Spirou4D** [comment]
Yes yu're right, I have to watch this! Sure!
Byebye
At soon.
Patrick

---

Patrick DepoixArchitecte D.P.L.G.Historien-chercheur en histoire de
l'ArchitectureEx-Maître de conférence de l'Ecole d'Architecture de
Lille-Région NordSitArchi-ReaderNewS
<http://www.google.com/reader/shared/user%2F04161245489718164963%2Fstate%2Fcom.google%2Fstarred>

http://www.linkedin.com/pub/patrick-depoix/40/b3b/542136, rue d'Esquermes59000
LilleFranceTel   (+33/0) 952 51 33 25Port  (+33/0) 06 23 13 73 71
Skype:oikakeruPour répondre --> Mailto:patrick.depoix@gmail.com
<http://---%20http://www.linkedin.com/pub/patrick-depoix/40/b3b/542%20Patrick%20Depoix%20Architecte%20D.P.L.G.%20Historien-chercheur%20en%20histoire%20de%20l%27Architecture%20Ex-Ma%C3%AEtre%20de%20conf%C3%A9rence%20de%20l%27Ecole%20d%27Architecture%20de%20Lille-R%C3%A9gion%20Nord136,%20rue%20d%27Esquermes%2059000%20Lille%20France%20Tel%20%20%20%28+33/0%29%20952%2051%2033%2025%20Port%20%20%28+33/0%29%2006%2023%2013%2073%2071%20Fax%20%20%28+33/0%29%20826%2070%2004%2040%20Skype:oikakeru%20%20Pour%20r%C3%A9pondre%20--%3E%20Mailto:patrick.depoix@free.fr>

2016-08-16 15:12 GMT+02:00 Dealga McArdle <notifications@github.com>:
